### ISSUE TITLE
Change operator framework imports to 'import ops' style

### ISSUE THREAD

**Issue by erik78se** [dwellir-public/polkadot-operator#25]
Change the import style to reflect the changes to ops upstream library.

See: https://github.com/erik78se/juju-operators-examples/pull/13

As part of [canonical/operator#921](https://github.com/canonical/operator/issues/921), we're updating the docs to use the now-recommended "import ops" style, that is, instead of:

```python
from ops.charm import CharmBase
from ops.main import main
class MyC(CharmBase):
    ...
if __name__ == "__main__":
    main(MyC)
```

We prefer people do:

```python
import ops
class MyC(ops.CharmBase):
    ...
if __name__ == "__main__":
    ops.main(MyC)
```

This PR updates all of the charm.py files to use this style. Since these are referred to from the machine charm tutorial, it would be ideal if they matched the preferred style, so that it's what new charmers are exposed to.

A few unused imports are also removed.

**Comment by jakobilobi** [comment]
I think the second code box should be

```python
import ops

class MyC(ops.charm.CharmBase):
    ...
if __name__ == "__main__":
    ops.main.main(MyC)
```

E.g. the intermediate sub-package step was skipped in the example.

**Comment by jakobilobi** [comment]
Question: should we implement this for all the charms in [dwellir-public/ops](https://github.com/dwellir-public/ops) as well?

**Comment by erik78se** [comment]
I think it makes sense to align.

**Comment by jakobilobi** [comment]
PS. VS Code might give you red squiggly lines for running `ops.main(...)` but it should be fine: https://github.com/canonical/operator/blob/b9194cadb77e1f8f1bceaa4f4232fafdd327dbcd/ops/main.py#L448C16-L448C16

**Comment by jakobilobi** [comment]
Done in https://github.com/dwellir-public/polkadot-operator/pull/31/commits/d6aa353973b849f6aea478bc0a2485cf8d572b84
